lab50: true
lab50:
  window:
    - editor
    - readme
    - terminal
    lab50:
  files:
    - !include foo.c
    - !include foo.h
    {% next %}
{% next "Step 2" %}
{% spoiler %}
The Answer to the Great Question... 
Of Life, the Universe and Everything...
Is...
Forty-two.
{% endspoiler %}

{% video https://www.youtube.com/watch?v=oHg5SJYRHA0 %}
